# Generated by Django 6.0.4 on 2026-04-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='experience_years',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='students_enrolled',
            field=models.IntegerField(default=565),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='teachers_count',
            field=models.IntegerField(default=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='total_branches',
            field=models.IntegerField(default=22),
        ),
    ]
